### ISSUE TITLE
Support to slot nested

### ISSUE THREAD

**Issue by icaioincau** [eddyerburgh/avoriaz#21] opened 2017-03-28 12:52 UTC
Hi, did avoriaz support slot inside mounted component? How I can test a component with slots?

https://vuejs.org/v2/guide/components.html#Content-Distribution-with-Slots

**Comment by eddyerburgh** [comment] 2017-03-28 14:36
Hi, it should do. There's a test in avoriaz for normal slots:

SlotParent.vue:
```vue
<template>
  <SlotChild>
    <h1 slot="header">Here might be a page title</h1>
    <p>A paragraph for the main content.</p>
    <p>And another one.</p>
    <p slot="footer" class="slot-footer-content">Here's some contact info</p>
  </SlotChild>
</template>

<script>
import SlotChild from './SlotChild.vue';
export default {
  name: 'SlotParent',
  components: {
    SlotChild,
  },
};
</script>
```

SlotChild.vue:
```vue
<template>
  <div class="container">
    <header>
      <slot name="header"></slot>
    </header>
    <main>
      <slot></slot>
    </main>
    <footer>
      <slot name="footer"></slot>
    </footer>
  </div>
</template>

<script>
export default {
  name: 'SlotChild',
};
</script>
```

find.spec.js
```javascript
  it('returns an array of Wrapper of elements matching class selector passed if they are declared inside a slot', () => {
    const wrapper = mount(SlotParent);
    const children = wrapper.find('.slot-footer-content');
    expect(children.length).to.equal(1);
  });
```

You can see the test here: https://github.com/eddyerburgh/avoriaz/blob/master/test/unit/specs/mount/find.spec.js

If you're having problems with nested slots, post the component here and I will get a fix up

**Comment by iCaio** [comment] 2017-03-28 16:29
Hi Eddy, my component is like this:

```
<template>
  <section class="tab-container">
    <ul class="tab-nav">
      <li v-for="item in items">
        <button
          class="button"
          role="tab"
          @click="selectItem(item.name)">{{ item.label }}</button>
      </li>
    </ul>
    <div class="tab-body">
      <slot></slot>
    </div>
  </section>
</template>
```

In the test, I want to add some HTML to the slot.


Actually  I am writing testing like this: 

```
describe('TabContainer', () => {
  let tabContainer = {};
  beforeEach(() => {
    const Ctor = Vue.extend(TabContainer)
    tabContainer = new Ctor({
      render: h => h('div', [h('tabContainer', {
        props: {
          defaultItem: 'tab1'
        }
      }, [h('tabItem', {
        props: {
          label: 'tab1 label',
          name: 'tab1'
        }
      }, [h('p', 'Sasha')]), h('tabItem', {
        props: {
          label: 'tab2 label',
          name: 'tab2'
        }
      }, [h('p', 'Xuxa')])])]),
      components: {
        tabContainer: TabContainer,
        tabItem: TabItem
      }
    }).$mount();
  })
```

Is there a way to append new `<p>` using avoriaz? Or I still need to create a helper component like the Ctor for it? 

PS: I am loving your project and changing some old test to use this one.

**Comment by eddyerburgh** [comment] 2017-03-29 11:49
@iCaio thanks

You should be able to add a p tag with mount:

```javsacript
import { mount } from 'avoriaz';

const wrapper = mount(TabContainer, {
  {
      render: h => h('div', [h('tabContainer', {
        props: {
          defaultItem: 'tab1'
        }
      }, [h('tabItem', {
        props: {
          label: 'tab1 label',
          name: 'tab1'
        }
      }, [h('p', 'Sasha')]), h('tabItem', {
        props: {
          label: 'tab2 label',
          name: 'tab2'
        }
      }, [h('p', 'Xuxa')])])]),
      components: {
        tabContainer: TabContainer,
        tabItem: TabItem
      }
})
```

I don't have much experience with

**Comment by iCaio** [comment] 2017-03-29 12:52
Thanks @eddyerburgh, I will close this issue.

**Comment by pearofducks** [comment] 2017-05-05 11:10
I'm trying to test slots as well, this code doesn't seem to do anything (in terms of adding a p-tag to the slot):

```
import { mount } from 'avoriaz';

const wrapper = mount(TabContainer, {
  components: {
    'pTag': {
      template: '<p></p>'
    }
})
```

If I then try to `wrapper.find('p')`, nothing is found.

**Comment by eddyerburgh** [comment] 2017-05-05 11:32
Can you post your component? I'll debug and see what's going on

**Comment by pearofducks** [comment] 2017-05-05 11:39
Invited you to https://github.com/pearofducks/lolsotemporary

Testing `src/components/Collapse.vue`
Using `test/Collapse.spec.js`

I'm actually using named slots, but even a single slot seems angry. :)

**Comment by eddyerburgh** [comment] 2017-05-05 12:38
Would you be able to get a smaller working example? 

There are tests for slot components in avoriaz, so there must be something else going on here

If not I'll have a proper look over the weekend

**Comment by icaioincau** [comment] 2017-05-05 12:44
I have used slot and worked well:

```
 mount(IdField, {
      propsData: {
        icon: 'vader-helmet'
      },
      render: h => h('idField', [h('idField', {
      }, [h('roundButton', {
      }, [h('p')])])]),
      components: {
        idField: IdField,
        roundButton: RoundButton
      }
    })
  });
```

But this week I can`t do the same with named slots :(

How can I fill a name slot in my IdField with this test?

**Comment by pearofducks** [comment] 2017-05-05 12:58
No problem, just pushed:

```
src/components/SimpleSlot.vue
test/SimpleSlot.spec.js
```

**Comment by icaioincau** [comment] 2017-05-05 16:02
@pearofducks Do you have an example of named slots?

**Comment by pearofducks** [comment] 2017-05-05 16:53
@icaioincau - not a working unit test of them! :)

**Comment by eddyerburgh** [comment] 2017-05-05 18:29
Just release v1.12.0, which adds support for a [slots option on mount](https://eddyerburgh.gitbooks.io/avoriaz/content/api/mount/) 🚀

For default slot behavior:

```js
import SomeComponent from './SomeComponent.vue'
import { mount } from 'avoriaz';

const wrapper = mount(TabContainer, {
  slots: {
    default: SomeComponent
})
```

To match named slots:

```js
const wrapper = mount(TabContainer, {
  slots: {
    'first-slot': Component,
    'second-slot': AnotherComponent
})
```

It takes a component. So if you just want to test a simple template, you'll need to use `vue-template-compiler`:

```
npm install --save-dev vue-template-compiler
```

In the test:

```js
import { compileToFunctions } from 'vue-template-compiler';
import { mount } from 'avoriaz';

const CompiledTemplate = compileToFunctions('<div />');

const wrapper = mount(TabContainer, {
  slots: {
    default: CompiledTemplate
})
```

Sorry for the confusion in earlier comments. I don't use slots very often, so didn't realize you were asking to inject slots into the wrapper.

**Comment by pearofducks** [comment] 2017-05-05 19:49
Confirmed working with named slots, thanks for the quick feature addition - that's awesome!

**Comment by pearofducks** [comment] 2017-05-06 06:55
Seems any call to `update()` breaks slots? Commenting out `simple.update()` works.

(I'm actually trying to get `v-if` and slots working in tests, but I got down to this test case not working)

```
test('renders stuff', async t => {
  const simple = await mount(Simple, {
    slots: {
      default: compileToFunctions('<h1 class="test-title">test-title</h1>')
    }
  })
  simple.update()
  const slottedHeader = simple.find('h1')[0]
  t.true(slottedHeader.is('h1'))
})
```

```
<template>
  <article class="collapse">
    <div class="collapse-content">
      <slot></slot>
    </div>
  </article>
</template>
```

**Comment by eddyerburgh** [comment] 2017-05-07 08:12
Thanks for the detailed bug report.

I went down a bit of a rabbit hole there. I thought I'd found a bug in Vue, cloned the repo and added a test ready for a PR. 

Turns out that $slots.default should be an array of vNodes!

So this should work:

```js
import avoriaz, { mount } from 'avoriaz'
import test from 'ava'
import { compileToFunctions } from 'vue-template-compiler'
import SimpleIf from '../src/components/SimpleIf.vue'

test('renders stuff', async t => {
  const simple = await mount(SimpleIf, {
    slots: {
      default: [compileToFunctions('<h1 class="test-title">test-title</h1>')]
    }
  })
  simple.vm.show()
  simple.update()
  const slottedHeader = simple.find('h1')[0]
  t.true(slottedHeader.is('h1'))
})
```

**Comment by pearofducks** [comment] 2017-05-07 10:05
Confirmed working on both default and named slots!

**Closed** 2017-05-07 18:45 UTC
Labels: enhancement

**Comment by icaioincau** [comment] 2017-05-08 17:15
Guys you are awesome, thank you so much @eddyerburgh

**Comment by viko16** [comment] 2017-09-08 02:14
Excuse me, I would like to know why the example code above use `async/await`, is `avoriaz.mount` an asynchronous function ?

**Comment by eddyerburgh** [comment] 2017-09-08 04:59
No it's not async
