### ISSUE TITLE
Spy or stub methods before mount

### ISSUE THREAD

**Issue by keligijus** [eddyerburgh/avoriaz#31] opened 2017-04-24 10:29 UTC
I've got some methods that are called on created, mounted events. I can't seem to be able to spy on them properly (or make stubs).

What I tried so far is, is spying on methods of pre mounted element and then checking if the spy was called. This doesn't work even when the actual method was called (tested by adding simple consolel.og)

Example:
```
it('calls myMethod when mounted', () => {
  const spy = sinon.spy(myComponent.methods, 'myMethod')
  const wrapper = mount(myComponent, { propsData, store })
  expect(spy.called).to.be.true // AssertionError: expected false to be true
})
```

Using Karma, Mocha and Sinon. I hope this is enough info and appropriate place to ask this.

**Comment by eddyerburgh** [comment] 2017-04-24 10:39
Hi, can you post your component code?

**Comment by keligijus** [comment] 2017-04-24 10:45
Hi, sure. I've removed html and a few methods, as they do not seem to be relevant for this.

```
<template>
  <div  v-bind:class="{'is-editing': isEditing}">
    <!-- html... -->
  </div>
</template>

<script>
export default {
  name: '',
  props: ['isEditing', 'message'],
  data () {
    return {
      msg: ''
    }
  },
  created () {
    if (!this.isEditing) this.getAutosavedDraft()
  },
  watch: {
    $route () {
      this.focusOnComposer()
      this.getAutosavedDraft()
    }
  },
  computed: {
    composerId () {
      return this.isEditing ? `id-${this.message.id}` : 'message-composer'
    }
  },
  mounted () {
    if (this.message && this.message.message) this.msg = this.message.message
    this.focusOnComposer()
  },
  methods: {
    getAutosavedDraft () {
      var route = this.$route.params.channel
      var message = this.getDraft(route)
      this.msg = message
    },
    focusOnComposer () {
      const composerElement = document.getElementById(this.composerId)
      if (composerElement !== null) composerElement.focus()
    }
  }
}
</script>
```

**Comment by eddyerburgh** [comment] 2017-04-24 11:28
This test works for me - 

```
it('calls changeMessage on mount', () => {
  const spy = sinon.spy(Foo.methods, 'focusOnComposer')
  mount(Foo)
  expect(spy.called).to.be.true
});
```
There must be something else going on here.

Can you link me to the full repo?

**Comment by keligijus** [comment] 2017-04-24 11:31
Thanks @eddyerburgh, you must be right. It's not an open repo, I'll have to make a copy of it without sensitive parts.

**Comment by keligijus** [comment] 2017-04-26 11:14
I've done more testing and rewriting of tests and am now leaning towards idea that it's a problem with Sinon (or how I use it).

Still, I've made a repo to test this out. If you get a chance, please have a look at it.

https://github.com/keligijus/vue-stub-demo/  test name __focuses on composer *issue on Github*__, line 156

I am also going to open an issue on Sinon with this.

**Comment by eddyerburgh** [comment] 2017-05-07 18:57
Hi @keligijus 

Did you manage to solve your problem? I can have a look into it if not 😁

**Comment by keligijus** [comment] 2017-05-08 10:38
Hi @eddyerburgh! No I haven't. I had to find a workaround for this.

I've noticed that this happens on when the component has mixins. If I remove them, it goes away. Also, it seems that it may be a problem with Sinon.

I've also discovered, that the real problem is not being unable to sub a methot, but that the callCount and called properties of Sinon are not being calculated. So even when the stub has been called, the callCount is still 0.

**Comment by eddyerburgh** [comment] 2017-05-08 11:03
Hmm, the problem could be with avoriaz. 

I don't use mixins and there aren't any tests in the library. 

Would you be able to create a simple example mixin that causes the stubs to break? Then I can add it as a test to avoriaz to ensure there are no problems handling mixins.

**Comment by keligijus** [comment] 2017-05-08 11:10
That's what I was told by the maintainer of Sinon. Here's [the issue on Sinon](https://github.com/sinonjs/sinon/issues/1385), I hope it explains the problem in more depth.

I've copied out my own code to make a case where it works without mixins, but fails when a mixin is added. This is the component: https://github.com/keligijus/vue-stub-demo/tree/trimmed/src/components/messages (has tests and the component).

If you run the tests, you will see that call count is working well on the first test, but fails for the second (even though the stub is called). Howerver, if you remove mixins, callCount works properly for both test.

If you want me to add a similar test to some other repo, just give me a link to it.

**Comment by eddyerburgh** [comment] 2017-05-08 12:18
Hi, so I've got a failing test set up 🎉. This is definitely a problem with avoriaz/ Vue. I'm going to ave a deeper look into it tonight.

**Comment by keligijus** [comment] 2017-05-08 12:24
Hey @eddyerburgh, sounds awesome! 🎉 

Thanks so much, I've been pulling my hair out for days now

**Comment by eddyerburgh** [comment] 2017-05-08 17:20
Success! 💥

This should be fixed in v[1.13.1](https://github.com/eddyerburgh/avoriaz/releases/tag/1.13.1).

Vue was cacheing the component, so instead of creating a new one with the correct stub, it was using an old version that had it's call count reset.

Now mount deletes any cached components before mounting 🚀

**Comment by keligijus** [comment] 2017-05-09 11:48
Edd, you're a legend man‼️

Thanks so much, now the joy of coding is back :man_dancing:

**Closed** 2017-05-09 13:38 UTC

**Comment by justincscott16** [comment] 2017-06-16 19:11
@eddyerburgh if you don't mind me pinging you for your opinion. I believe my issue is closely related with this but am unsure. I have a component that uses a mixin, and uses a method from that mixin on mount.

It looks like the test blows up because in the mixin method, it accesses uses the Vuex store, but is referencing the wrong `this`.

Not sure if this is related to this issue/fix at all, and I may have done very poorly trying to explain it. Here is a bare bones example of how the component/mixin are being used. And the error I am getting is `Cannot read property 'url' of undefined`. Anyways, thought I would ask if you might have any idea, if not or if it isn't really related, than that is okay too I will keep searching! Thanks a ton!

```javascript
// sampleMixin.js

module.exports = {
  methods: {
    getSomeData: function() {
      const url = this.$store.state.someData.url
    }
  }
}
```

```
// sampleComponent.js
<template>
  <div></div>
</template>

<script>
  import sampleMixin from '../mixins/sampleMixin'

  export default {
    name: 'sample-component',
    mixins: [sampleMixin],
    props: [someProp],

    mounted() {
      if (this.someProp) {
        this.sampleMixin()
      }
    }
  }
</script>
```

**Comment by eddyerburgh** [comment] 2017-06-16 22:08
It looks like `someData` is undefined. 

If you pass $store as a global with avoriaz it should work fine:

```js
const wrapper = mount(Hello, {
  globals: {
    $store: {state: {someData: {url: 'some url'}}}
  }
})
```

Are you using Vue.use(Vuex) in your tests? If you are, then the problem is that there is no someData module. You'll need to pass the store on mount:

```js
const store = new Vuex.Store({
  state: {
    someData: {url: 'some url'}
  },
})
const wrapper = mount(Component, { store })
```

Here's a detailed guide on testing vuex - https://www.coding123.org/mock-vuex-in-vue-unit-tests/. 

Unfortunately, Vuex adds $store using defineProperty, which means it can't be deleted/ overwritten with `mount.globals`. The solution would be to either not run Vue.use(Vuex) in your test, or pass your mount instance a store with the correct state.

**Comment by justincscott16** [comment] 2017-06-16 22:18
@eddyerburgh right, I am creating a store with getters defined. I possibly missed defining the store in the state before mounting, but I hadn't needed to previously. I will give that a shot and see what happens. Also, thanks for the vuex tutorial, although that had been my savior a few times already 😅
