### ISSUE TITLE
.html() is undefined when template root tag is <a>

### ISSUE THREAD

**Issue by podlebar** [eddyerburgh/avoriaz#157] opened 2017-10-11 12:06 UTC
the html() method returns a undefined when the root tag of a template is a link tag.
Vue does not give me any errors but could it be that the root element should not have any bindings attached or so?

Not working example:
```
    <template>
        <a
            class="teaser__link teaser__posterholder"
            :href="this.href"
            v-if="this.teaser && this.teaser.crops[1]"
        >
            <figure class="poster">
                <div class="poster__placeholder">
                    <img
                        src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                        :alt="this.title"
                        :data-srcset="teaserImageSrcSet"
                    >
                </div>
            </figure>
        </a>
    </template>

```

while this is working even the root tag is still not a block tag:
```
    <template>
        <span>
            <a
                class="teaser__link teaser__posterholder"
                :href="this.href"
                v-if="this.teaser && this.teaser.crops[1]"
            >
               ...........
            </a>
        </span>
    </template>
```

**Comment by willypt** [comment] 2017-10-17 11:29
```javascript
<template>
  <a :href="foo">Hello world</a>
</template>

<script>
  export default {
    name: 'foo',
    props: [
      'foo'
    ]
  };
</script>
```

```javascript
import Vue from 'vue'
import Testing from '@/components/Testing'
import { mount } from 'avoriaz';

describe('Test v-model', function () {
  it('check v-model value', function () {
    const wrapper = mount(Testing, {
      propsData: {
        'foo': 'initial value'
      }
    });
    console.log(wrapper.html())
  });
});
```
returns

```
LOG LOG: '<a href="initial value">Hello world</a>'
```

Can you please let us know the use case? It seems it's not a bug

**Comment by podlebar** [comment] 2017-10-17 13:21
@willypt 

here is the component: https://gist.github.com/podlebar/448d11a959a51a7373a71f24b531be7f
and here the test: https://gist.github.com/podlebar/469c1764ef2aa3f7c9bd760403ab2c4e

the first span in the component i would like to remove.. but when i remove it wrapper.html() is undefined.. with span it works good.

**Comment by willypt** [comment] 2017-10-18 02:17
hi @podlebar,
I've checked on your code and yes, it seems that after mounting and setting props forcefully via `setProps`, the dom in Avoriaz Wrapper is not re-rendered, even when I try `.update()` it. Will check later though.
```
LOG LOG: 'AVORIAZ', VNode{tag: undefined, data: undefined, children: undefined, text: '', elm: <!---->, ns: undefined, context: undefined, functionalContext: undefined, functionalOptions: undefined, functionalScopeId: undefined, key: undefined, componentOptions: undefined, componentInstance: undefined, parent: undefined, raw: false, isStatic: false, isRootInsert: true, isComment: true, isCloned: false, isOnce: false, asyncFactory: undefined, asyncMeta: undefined, isAsyncPlaceholder: false}
```

however, for the current workaround, if you try to setting the props when being **instantiated**, you can get the correct result
```javascript
describe('articleposter.vue', () => {
  it('Check generated HTML', () => {
    const wrapper = mount(Testing, {
      propsData: propsMock
    });
    expect(wrapper.html()).to.equal(expectedHTML);
  });
});
```

**Comment by eddyerburgh** [comment] 2017-10-18 06:17
This should be fixed in 6.0.1 🙌

**Comment by podlebar** [comment] 2017-10-18 06:21
thx a lot @eddyerburgh @willypt  👍

**Comment by willypt** [comment] 2017-10-18 08:02
Thanks for the fix @eddyerburgh ! 👍

**Closed** 2017-11-13 11:36 UTC
Labels: bug
